### ISSUE TITLE
20 limit ?

### ISSUE THREAD

**Issue by TanguyOrtegat** [maxux/toogoodtogo-watcher#3]
After further investigartion, i saw that the limit that the bot checks is 20. In my favorites i did see that i have more then 20 items in the list. So i looked at the code and i swa a loop through the items. So i don't understand how it is stuck at 20 items.

Any idea how come ?

**Comment by TanguyOrtegat** [comment]
found sollution:
https://github.com/maxux/toogoodtogo-watcher/blob/master/toogoodtogo.py#L145

change 20 to number you want

**Comment by maxux** [comment]
Did you tried to change ? Does it works when you increase it ? I didn't tried using more than 20, the original app limits to 20 by default.

**Comment by TanguyOrtegat** [comment]
like i said, fixed by increasing page number line 145
